spring.application.name=weather-api

weather.geocoding.base-url=${GEOCODING_BASE_URL:https://geocoding-api.open-meteo.com/v1}
weather.forecast.base-url=${WEATHER_BASE_URL:https://api.open-meteo.com/v1/forecast}

spring.codec.max-in-memory-size=1MB
server.tomcat.max-http-form-post-size=16KB

