spring.application.name=weather-api

weather.geocoding.base-url=${GEOCODING_BASE_URL:https://nominatim.openstreetmap.org}
weather.forecast.base-url=${WEATHER_BASE_URL:https://api.open-meteo.com/v1/forecast}

