apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: weather-api

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - pod-disruption-budget.yaml
  - network-policy.yaml

images:
  - name: weather-api
    newName: ghcr.io/justxt/weather-api
    digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
