apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: weather-api-ingress
  namespace: weather-api
  labels:
    app.kubernetes.io/name: weather-api
    app.kubernetes.io/part-of: weather-api
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: weather-api
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
