apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: weather-api
  namespace: weather-api
  labels:
    app.kubernetes.io/name: weather-api
    app.kubernetes.io/part-of: weather-api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: weather-api
